version: 1.0.{build}

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2019

environment:
  matrix:
    - PLATFORM: --host_platform //dotnet/toolchain:windows_amd64_3.0.100 --platforms //dotnet/toolchain:windows_amd64_3.0.100

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

install:
  - choco install bazel
  
build_script:
  - ver
  - bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m build %PLATFORM% //...

test_script:
  - bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m run %PLATFORM% //tests/examples/example_binary:hello.exe
  - bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m test %PLATFORM% --test_summary=detailed --test_output=all //... 
  # - cd examples\grpc
  # - bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m test --spawn_strategy=standalone //...
  # - cd ..\ef
  # - bazel --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m test --spawn_strategy=standalone //...


deploy: off

